# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/system_design/system_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design || ORIG_REF_NAME==system_design} -quiet] -quiet

# IP: bd/system_design/ip/system_design_processing_system7_0_0/system_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_processing_system7_0_0 || ORIG_REF_NAME==system_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_i2s_receiver_0_0/system_design_i2s_receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_i2s_receiver_0_0 || ORIG_REF_NAME==system_design_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_i2s_transmitter_0_0/system_design_i2s_transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_i2s_transmitter_0_0 || ORIG_REF_NAME==system_design_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_audio_formatter_0_0/system_design_audio_formatter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_audio_formatter_0_0 || ORIG_REF_NAME==system_design_audio_formatter_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_xbar_0/system_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_xbar_0 || ORIG_REF_NAME==system_design_xbar_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_ps7_0_axi_periph_2/system_design_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_ps7_0_axi_periph_2 || ORIG_REF_NAME==system_design_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/system_design/ip/system_design_rst_ps7_0_49M_2/system_design_rst_ps7_0_49M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_rst_ps7_0_49M_2 || ORIG_REF_NAME==system_design_rst_ps7_0_49M_2} -quiet] -quiet

# IP: bd/system_design/ip/system_design_proc_sys_reset_0_0/system_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_proc_sys_reset_0_0 || ORIG_REF_NAME==system_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_clk_wiz_1_0/system_design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_clk_wiz_1_0 || ORIG_REF_NAME==system_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_xbar_1/system_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_xbar_1 || ORIG_REF_NAME==system_design_xbar_1} -quiet] -quiet

# IP: bd/system_design/ip/system_design_axi_interconnect_0_0/system_design_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_axi_interconnect_0_0 || ORIG_REF_NAME==system_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_xlconcat_0_0/system_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_xlconcat_0_0 || ORIG_REF_NAME==system_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_clk_wiz_0_0/system_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_clk_wiz_0_0 || ORIG_REF_NAME==system_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_auto_pc_0/system_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_auto_pc_0 || ORIG_REF_NAME==system_design_auto_pc_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_auto_us_0/system_design_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_auto_us_0 || ORIG_REF_NAME==system_design_auto_us_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_auto_us_1/system_design_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_auto_us_1 || ORIG_REF_NAME==system_design_auto_us_1} -quiet] -quiet

# IP: bd/system_design/ip/system_design_auto_pc_1/system_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_auto_pc_1 || ORIG_REF_NAME==system_design_auto_pc_1} -quiet] -quiet

# XDC: bd/system_design/system_design_ooc.xdc
